getwd()
human = read.table("human2.txt", sep="\t", quote = "", stringsAsFactors = FALSE, header=TRUE)
dim(human)
str(human)
library(GGally)
library(ggplot2)
library(dplyr)
library(tidyr)

complete.cases(human)
dim(human)
summary(human)

# create a more advanced plot matrix with ggpairs(learning2014[-1])
p <- ggpairs(human, mapping = aes( alpha=0.3), lower = list(combo = wrap("facethist", bins = 20)))

# draw the plot
p

# calculate the correlation matrix and round it
cor_matrix<-cor(human) 

# print the correlation matrix
cor_matrix %>% round(2)  %>% print() 

library(corrplot)

cor.mtest <- function(mat, conf.level = 0.95){
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat <- lowCI.mat <- uppCI.mat <- matrix(NA, n, n)
  diag(p.mat) <- 0
  diag(lowCI.mat) <- diag(uppCI.mat) <- 1
  for(i in 1:(n-1)){
    for(j in (i+1):n){
      tmp <- cor.test(mat[,i], mat[,j], conf.level = conf.level)
      p.mat[i,j] <- p.mat[j,i] <- tmp$p.value
      lowCI.mat[i,j] <- lowCI.mat[j,i] <- tmp$conf.int[1]
      uppCI.mat[i,j] <- uppCI.mat[j,i] <- tmp$conf.int[2]
    }
  }
  return(list(p.mat, lowCI.mat, uppCI.mat))
}

res1 <- cor.mtest(human,0.95)
colSums(is.na(human))
human$GNI
human$mat_mor_rat
# visualize the correlation matrix
corrplot.mixed(cor_matrix,tl.cex=0.5,p.mat = res1[[1]], insig = "blank"
               ,mar=c(1,0,2,0),number.cex=0.7, title="Correlation between variables")

gather(human) %>% ggplot(aes(value)) + facet_wrap("key", scales="free") +
geom_bar() + theme (axis.text.x=element_text(angle=45, hjust=1, size=8))

##########################################################################
#pca
pca_human <- prcomp(human)
biplot(pca_human, choices =1:2, cex=c(0.8,1),col=c("grey40","deeppink2"))

s<-summary(pca_human)
s
pca_pr<-round(100*s$importance[2,], digits=1)
pca_pr
pc_lab<-paste0(names(pca_pr),"(",pca_pr,"%)")
biplot(pca_human, cex=c(0.8,1),col=c("grey40","deeppink2"),xlab=pc_lab[1],ylab=pc_lab[2])
##########################################################################

